### ISSUE TITLE
Fix Design Flaws in Footer

### ISSUE THREAD

**Issue by poofichu** [AIGA-Austin/website#1]
- [x] Link color for the footer is not accessible
- [x] Broken images

![image](https://cloud.githubusercontent.com/assets/6757613/16243618/bdfa1726-37bd-11e6-9473-c4214812f5a2.png)

**Comment by claymcclure** [comment]
I'll contact Tiia about this.

**Comment by poofichu** [comment]
Went ahead and just overrided the stylesheet to fix the link color and removed local sponsors as a widget for now.
