### ISSUE TITLE
Past Events = These need deleting

### ISSUE THREAD

**Issue by ghost** [AIGA-Austin/website#10]
Ergh. You have me to thank for these, sorry. Can we delete the two Pay Pal Tests out of the Past Events list? 

![screen shot 2016-07-16 at 8 27 05 am](https://cloud.githubusercontent.com/assets/20098954/16895058/2daa0aac-4b2f-11e6-8ba5-8d85ab823561.png)

**Comment by poofichu** [comment]
Testing Github/Slack integration....

**Comment by claymcclure** [comment]
I archived the two test events... hopefully that will remove them. For some reason I can't delete them in etouches.

**Comment by claymcclure** [comment]
Ok. So I cancelled the two events and unchecked the box that places events on the site. Let's hope this works

**Comment by poofichu** [comment]
Magic!  All gone!
