### ISSUE TITLE
Suggestion? Display events on home page similar to News Billboard widget

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#14]
This update from Tiia (hq) on the national Slack: 

> If you are interested in having your events display on the homepage the way the News Billboard widget displays news then you're in luck, cause now you can! Just add an Event Billboard widget to your homepage and select "grid" from the 'how you would like the events to display' dropdown.

I'm still trying to find an example of how events might render this way, but it might be nice to have them in this format above the news grid to help promote their visibility? Just a thought!

**Comment by claymcclure** [comment]
This is already in use on the site. Currently it is set to "slideshow" but can be changed to "grid"

**Comment by poofichu** [comment]
I would recommend changing to grid view.  That way our users can see all at once what we have coming up instead of having to scroll through a slider.

**Comment by claymcclure** [comment]
Changed to grid and it looks exactly like news posts. Is this what we want?

**Comment by poofichu** [comment]
Is there another layout for featured news?

I honestly don't hate it.  And it's faster loading for our users.

**Comment by southernroutes** [comment]
Hmm, I see now. Well, if we're going to do this we probably need to increase the size of the widget titles (Featured Events).

Also, might it be nice to have a (much shorter <300px) branded banner above to provide some context? I feel like the current 40px icon in the upper-left could use some help in that department.

**Comment by poofichu** [comment]
I think we're going to keep this to the slider and if there are any other widgets y'all want to include plz let me know!
