### ISSUE TITLE
MRK Scholarship Application

### ISSUE THREAD

**Issue by crystalglover** [AIGA-Austin/website#15]
Applications for the scholarship open on March 1! On that day or the day before, please make these updates to the MRKScholarship.org site:

Please replace "Applications Open March 1, 2017" (at the top) with "Apply Now Through May 14, 2017" and link to https://aigaaustin.typeform.com/to/XA8HjA

Please also update the copy under the Applications header to read, "Applications open now through May 14, 2017. To apply, please click here." with the same link.

Thank you!

**Comment by claymcclure** [comment]
Fixed and pending review.
