### ISSUE TITLE
Giving Voice on Website

### ISSUE THREAD

**Issue by maranda-AIGA** [AIGA-Austin/website#21]
Hey Jessica, Can we get this up on the website? 
https://docs.google.com/document/d/15D2nYkhm9lwdNdjrgPHIXD7V1lU9uRkIp--d6w5_7gw/edit?usp=sharing

I'm working on getting a hero image.

**Comment by maranda-AIGA** [comment]
![givingvoice_header](https://user-images.githubusercontent.com/30530540/28757547-2084d04a-754b-11e7-8566-869fac950431.png) @poofichu image for the Giving Voice

**Comment by poofichu** [comment]
Posted to the blog!
http://austin.aiga.org/call-for-mentors-giving-voice-2017/
