### ISSUE TITLE
Jeromy Lund Interview

### ISSUE THREAD

**Issue by maranda-AIGA** [AIGA-Austin/website#22]
Hey Jessica, Could we get this up on the blog by Wednesday? 

I will have Jeromy Lund's image soon. 

https://docs.google.com/document/d/1gG1aBaEtJJ53T8vAzOfukSuiUOIDoL9SM3tTk0ivJXY/edit?usp=sharing

**Comment by maranda-AIGA** [comment]
@poofichu here's the image :) 
![untitled-4](https://user-images.githubusercontent.com/30530540/28902835-1bdbe2b2-77c7-11e7-9dfb-9c7de27805a0.jpg)

**Comment by poofichu** [comment]
Blog page created:
http://austin.aiga.org/a-conversation-with-maura-rose-2017-recipient-jeromy-lund/

And added to scholarship page:
http://austin.aiga.org/scholarships/aiga-maura-rose-kampa-scholarship/
