### ISSUE TITLE
Small Talks Recap

### ISSUE THREAD

**Issue by maranda-AIGA** [AIGA-Austin/website#25]
Hey Jessica, 

Can we get this up on the blog: https://docs.google.com/document/d/1uT8kZC9ttWqZ884atEbEM-XEEEx2N7OHEhaTFIhuYVY/edit?usp=sharing

**Comment by maranda-AIGA** [comment]
@poofichu here is the image: 
![smalltalks](https://user-images.githubusercontent.com/30530540/29091374-5d870a86-7c48-11e7-9586-a58baa682c45.png)

**Comment by poofichu** [comment]
Posted on the blog!
http://austin.aiga.org/aiga-austin-ux-small-talks-argodesign-integrated-reality-recap-resources/
