### ISSUE TITLE
Should be "AIGA Austin Presents" not AIGA Present

### ISSUE THREAD

**Issue by maranda-AIGA** [AIGA-Austin/website#27]
Found a small error in the title after Cat changed it, it should be Presents, not Present: https://austin.aiga.org/event/aiga-austin-present-mark-my-word-a-typeed-workshop/

**Comment by poofichu** [comment]
Updated on the site and Eventbrite!

New URL:
https://austin.aiga.org/event/aiga-austin-presents-mark-my-word-a-typeed-workshop/
