### ISSUE TITLE
Add Changemaker event to website 

### ISSUE THREAD

**Issue by maranda-AIGA** [AIGA-Austin/website#28]
Hey! Looks like this is ready to go on the website..they're still finalizing the panelists: https://austindesignweek.org/schedule/aiga-austin-changemaker-series-making-design-for-good-a-part-of-your-career

**Comment by poofichu** [comment]
https://austindesignweek.org/schedule/making-design-for-good-a-part-of-your-career

**Comment by poofichu** [comment]
Up on the site! https://austin.aiga.org/event-internal/making-design-for-good-a-part-of-your-career/
