### ISSUE TITLE
Create Changemaker landing page at austin.aiga.org/changemaker

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#32]
![changemaker-hero-image-2000x1200](https://user-images.githubusercontent.com/585531/32558744-29d4c500-c46b-11e7-8e94-c6815213a96e.png)

2000 x 1200 hero image attached.

Page Title: Changemaker Series

Page content:

**CHANGEMAKER** is an AIGA Austin initiative that unites teams of creative professionals with nonprofits and social change organizations to use design thinking, sustainable frameworks and creative tools to help advance their mission. Inspired? [Sign up here](https://aigaaustin.typeform.com/to/snA08z) to learn how you can help build a movement for change.

**Comment by poofichu** [comment]
Page added to the site! https://austin.aiga.org/events/changemaker/
