### ISSUE TITLE
Content for Changemaker Happy Hour event

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#34]
Copy for the Changemaker Happy Hour Event:
https://docs.google.com/document/d/19RJyiE2cpMk4zJe-2qI4To-ZPM4hdpGKeuofZVVcPDQ/edit?usp=sharing

This event is free for all, but we'd like to get an EventBrite set up for RSVPs and check-ins.

Image attached. 

![changemaker-event-hero-image-2000x1200](https://user-images.githubusercontent.com/585531/36394898-f83ccd28-157b-11e8-8347-8782020e71a3.png)

**Comment by poofichu** [comment]
Pushed to the website!
