### ISSUE TITLE
Link text on Changemaker landing & FAQs pages to March 1st Happy Hour event page

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#35]
Once the happy hour event page is live, link the text below to that page:

On the main CM landing page:
https://austin.aiga.org/events/changemaker/

Second paragraph, second sentence, link the text that reads: "Changemaker Happy Hour on March 1st"
and
fourth paragraph, link the text that reads "March 1st Changemaker Happy Hour"
to the page for that event. 

On the CM FAQs page:
https://austin.aiga.org/events/changemaker/faq/

**General FAQs** > **Q: How long does this program last?**
First bullet, link the text that reads: "Changemaker Happy Hour event" to the page for that event. 
Delete "(Coming soon!)"

**Potential Creative Team Member FAQs** > **Q: I can’t commit to a project...**
First paragraph, link the text that reads: "Changemaker Happy Hour" to the page for that event.

**Comment by poofichu** [comment]
Links updated!

**Comment by southernroutes** [comment]
Thanks! Couple of things:

- On main CM page, fourth paragraph, the link is not resolving
- On Potential Creative Team Member FAQs > "Q: I can’t commit to a project. Is there another way I can give back?", Changemaker Happy Hour link works, but the link text has some extra characters in front of it (“>).

**Comment by poofichu** [comment]
Derp! fixed!
