### ISSUE TITLE
MRK Scholarship Page Updates!

### ISSUE THREAD

**Issue by crystalglover** [AIGA-Austin/website#38]
Howdy! It's that time of year again. Can you make these edits by Friday morning? I'm going to see if the comms team can send an announcement email on Friday afternoon. It's okay if you'd rather do these earlier than Friday—it'd be great if someone sneaks in an application early :P 

Please update "Applications for 2018 open on March 2" to something like "Applications for 2018 are now open! Apply now." with a link to the Typeform: https://aigaaustin.typeform.com/to/kOK1Tx

Under the Applications headline below, please update to read "Applications for 2018 are open from March 2 through May 13. Apply now!" with a link to the Typeform: https://aigaaustin.typeform.com/to/kOK1Tx

Thanks!

cg

**Comment by poofichu** [comment]
Updated!

**Comment by crystalglover** [comment]
Woot! So I literally just got the final artwork for this year's poster as soon as you sent that, plus a change in title for David Kampa:

- Could you swap the image for this one? https://drive.google.com/open?id=1p7o6VfoRFlnSIREaGoykKZP25Q1DgCrl

- Could you update the second paragraph to read: "One student will be awarded a one-time gift of $1,500 toward tuition or other college expenses, plus a mentorship with David Kampa, award-winning design director at McGarrah Jessee."

Thank you!!

**Comment by crystalglover** [comment]
Oops, I commented on the wrong issue! Here is the edit to the MRK page:

Under the Awards header, could you update the copy to read: "One student will be awarded a one-time gift of $1,500 toward tuition or other college expenses. The student will also receive a mentorship with David Kampa, award-winning design director at McGarrah Jessee."

Thanks!

**Comment by poofichu** [comment]
done!
