### ISSUE TITLE
MRK Scholarship News Article

### ISSUE THREAD

**Issue by crystalglover** [AIGA-Austin/website#39]
Can we add a news story for the MRK Scholarship? Here is copy and an image: https://docs.google.com/document/d/1I862ofbCEHPjQPlQpkDW7LJ7rf5F3M_MVm2RD2Z3Y2s/edit?usp=sharing

Thanks!

cg

**Comment by poofichu** [comment]
https://austin.aiga.org/event-internal/now-accepting-applications-for-the-2018-maura-rose-kampa-scholarship/

**Comment by crystalglover** [comment]
Woot! So I literally just got the final artwork for this year's poster as soon as you sent that, plus a change in title for David Kampa:

Could you swap the image for this one? https://drive.google.com/open?id=1p7o6VfoRFlnSIREaGoykKZP25Q1DgCrl

Could you update the second paragraph to read: "One student will be awarded a one-time gift of $1,500 toward tuition or other college expenses, plus a mentorship with David Kampa, award-winning design director at McGarrah Jessee."

Thank you!!

**Comment by poofichu** [comment]
Updated!
