### ISSUE TITLE
Change Out Contact Us Form to use Ninja Forms

### ISSUE THREAD

**Issue by poofichu** [AIGA-Austin/website#4]
- [ ] Look at test contact form to figure out if we need the paid version or not

**Comment by claymcclure** [comment]
At the leadership conference, we discussed GravityForms as being a good solution. I think nationals pays for the full version and it has logic/conditional statement capabilities. I'm looking into it. We will need to completely re-do all of our forms AND there is a misconfiguration thing on our WP for Contact Form 7.
