### ISSUE TITLE
Add links to Change Org application on CM landing page and FAQs page

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#40]
On the main Changemaker landing page, under the heading **Apply To Be A Changemaker**, remove the text that reads "Nonprofits and social Change Organizations, find creative ideas for your challenging problems." as well as the bulleted text that reads "Applications for Nonprofit and Change Organization Partners open on March 1st"

Replace those with an H3 link that says:

**[Application for Nonprofit and Change Organization Partners →](https://aigaaustin.typeform.com/to/VEOMzT)**

And for the FAQs page, under the heading **Q: How do I participate in this? How do I sign up?**, link the text that reads "[Application for Nonprofit and Change Organization Partners](https://aigaaustin.typeform.com/to/VEOMzT)" and remove the last few words in that line that read "opens on March 1st"

Also, can you pls add it to the top of the right sidebar just like Seattle has? Example:
 
![image](https://user-images.githubusercontent.com/585531/36814293-b5b791b8-1c9c-11e8-9676-165105133040.png)

Our mouse type underneath the application link should say "Application closes Sunday, April 15th at 11:59 p.m. CST."

Any possibility of having this done by EOD Thurs would result in a shower of rainbows and flying toaster kitties. 

Thanks!!

**Comment by poofichu** [comment]
Updated!!
