### ISSUE TITLE
Changemaker Landing Page Edits

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#41]
Changemaker Landing Page > 2nd paragraph: 

- delete the words "Come to the Changemaker Happy Hour on March 1st and " 
- capitalize "subscribe"
- change the URL for the link text that reads "Subscribe to email updates" to http://eepurl.com/dm5Cg1

Changemaker Landing Page > 4th paragraph:

- remove the text and link that reads "This year’s cause will be announced at the March 1st Changemaker Happy Hour."
- replace with the following header and copy:

## 2018 Changemaker Series Cause: Homelessness

The homeless issue in Austin has become commonplace despite how dire the situation can be for many of our citizens. Austin’s homeless population has remained fairly steady, last counted at 2036 by Austin ECHO, over the last few years. Around 40% of those individuals live unsheltered at night. In our community, the unsheltered population is largely made up of single males, African Americans, and people aged 45 – 65. One person or organization alone cannot solve the housing and homelessness issue in Central Texas, but we all can help.

This year’s inaugural Changemaker Series will focus on this important issue. The series runs from June to September and will unite teams of creative professionals with nonprofits and social change organizations to use design thinking, sustainable frameworks and creative tools to help advance their missions. Join us and utilize your skills for your community. This is a great opportunity to collaborate and with a diverse set of people, learn new skills, and above all give back.

Changemaker Landing Page > Apply To Be A Changemaker:

- remove the sentence that begins "Creative professionals, use your design..."
- remove the bullet that reads "Applications for Creative Team Participants open on March 1st"
- below the link that reads "Application for Nonprofit and Change Organization Partners" add a single line (in bold) "**Find creative ideas for your challenging problems.**"
- below the paragraph that begins "We want nonprofits and social Change Organizations to apply..." add the following header/link and copy:

## [Application for Creative Team Participants »](https://aigaaustin.typeform.com/to/XwpqHj)

**Volunteer to use your design superpowers for good and learn new skills to help grow your tool chest!**
We're looking for designers and creative professionals who want to apply to be part of the series. We’re looking for people who are great team players, experimenters and problem solvers; and who are willing to devote time to be a on a team using human-centered design skills to tackle a project for an organization over the summer.

Changemaker Landing Page > Stay Informed:

- change the URL for the link text that reads "Sign-up for our email list" to http://eepurl.com/dm5Cg1
- change the text that reads "Design for Good events and initiatives!" to "Changemaker Series!"

Changemaker Landing Page > Right Sidebar:

- below the text/link "Application for Nonprofit and Change Organizations," add a link: [Application for Creative Team Participants](https://aigaaustin.typeform.com/to/XwpqHj)

**Comment by poofichu** [comment]
Okay, changes made.  @southernroutes can you double check?

**Comment by southernroutes** [comment]
This all looks good to me! Can you make the link in the sidebar to the "Application for Creative Team Participants" open in a new window? Thanks!

**Comment by poofichu** [comment]
Updated!
