### ISSUE TITLE
Revise Changemaker home page banner application deadline to April 30th

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#42]
On the Changemaker home page banner, change the event **end date** to April 30th:
https://austin.aiga.org/event-internal/now-accepting-applications-to-be-a-changemaker/

Change the day/date at the bottom of the page to "Monday, April 30th" in the text that reads "

"Applications for creative professionals and nonprofits/Change Organizations close **Sunday, April 15th** at 11:59 p.m. CST."

Is it possible to have the "Apply today!" button in the sidebar go directly to our TypeForm link (https://aigaaustin.typeform.com/to/XwpqHj)?

![image](https://user-images.githubusercontent.com/585531/38755936-43c9ad30-3f2d-11e8-9ea8-ed42a629935b.png)

**Comment by poofichu** [comment]
Updated!
