### ISSUE TITLE
Revise Changemaker landing page application deadline to April 30th

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#43]
On the CM landing page, change day/date to "Monday, April 30th" in the text that reads "Applications for creative professionals and nonprofits/Change Organizations close **Sunday, April 15th** at 11:59 p.m. CST."

and in the sidebar, where it says "Applications close **Sunday, April 15th** at 11:59 p.m. CST."

**Comment by poofichu** [comment]
Updated!
