### ISSUE TITLE
Revise Changemaker FAQs page application end dates

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#44]
On the CM FAQs page > General FAQs:

Under the heading "Q: How long does this program last?" change the date to "April 30th" in the bullet that reads "April 15th: Applications for volunteer creative team members and nonprofits/social Change Organizations due"

Under the heading "Q: How do I participate in this? How do I sign up?"change the date to "April 30th" in the text that reads "Applications for volunteer creative team members and nonprofits/social Change Organizations must be submitted by **April 15th.**"

In the sidebar, change the day/date to "Monday April 30th"

"Applications close **Sunday, April 15th** at 11:59 p.m. CST."

**Comment by poofichu** [comment]
Revised!
