### ISSUE TITLE
Remove Change Org application links 

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#45]
Hi, can you please remove the link to the applications for **change orgs** and replace it w/ the following text:

Application for Nonprofit and Change Organization Partners is closed.

This should happen in the sidebar of both the landing page and FAQ as well as on:

- the landing page under the heading "Apply To Be A Changemaker"
- the FAQs page under the heading "Q: How do I participate in this? How do I sign up?"

**Comment by poofichu** [comment]
Updated!
