### ISSUE TITLE
Remove Creative Application links from Changemaker landing page and FAQs Page

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#46]
Hi, I should have submitted both of these sooner. :-(

Applications close tonight at midnight. Can you please remove this block of copy/links from the sidebar of both the CM landing page and FAQs page: 

• Application for Nonprofit and Change Organization Partners
• Application for Creative Team Participants

Applications close Monday, April 30th at 11:59 p.m. CST.

...and replace it with this copy:

Applications for the 2018 Changemaker Series are now closed. [Sign-up for our email list](http://eepurl.com/dm5Cg1) to stay up-to-date on AIGA Austin’s Changemaker Series!

--------

On the CM landing page, please remove this entire block of content:

Apply To Be A Changemaker
Application for Nonprofit and Change Organization Partners »
Find creative ideas for your challenging problems.

We want nonprofits and social Change Organizations to apply to be part of the series. We’re looking for committed clients who are able to devote time to the series, share knowledge about their organization and mission, and actively collaborate with their creative professional team members.

Application for Creative Team Participants »
Volunteer to use your design superpowers for good and learn new skills to help grow your tool chest!

We’re looking for designers and creative professionals who want to apply to be part of the series. We’re looking for people who are great team players, experimenters and problem solvers; and who are willing to devote time to be a on a team using human-centered design skills to tackle a project for an organization over the summer.

-----------

On the FAQs page, please remove the hyperlink to the application, but leave the text under "Q: How do I participate in this? How do I sign up?"

Applications for volunteer creative team members and nonprofits/social Change Organizations must be submitted by April 30th.

Thanks!!

**Comment by poofichu** [comment]
Updated!
