### ISSUE TITLE
Set up unlisted (not public) EventBrite reg form for Changemaker Weekend Workshop

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#49]
Full details here:

https://docs.google.com/document/d/1vy3lNd92l-sv3YpdHlY8_Bb3VM36kWJLzi8lZviDXuo/edit?usp=sharing

Please let me know if you need any other info. Thanks!

**Comment by poofichu** [comment]
Do you have a banner image you want to use for this?

**Comment by southernroutes** [comment]
Hey! You can use the same one from our website landing page (attached,
might not be super high-res).

Thanks
