### ISSUE TITLE
Update open positons

### ISSUE THREAD

**Issue by maranda-AIGA** [AIGA-Austin/website#51]
Can we update this posting: https://austin.aiga.org/event-internal/aiga-board-nominations-2018/

- Just include Social Media chair + Email Chair 
- Closing date: June 26

Oen is updating the typeform

**Comment by maranda-AIGA** [comment]
Typeform is up to date

**Comment by maranda-AIGA** [comment]
Here's the social chair description: 

The Social Media Chair is responsible for posting and updating all social media on (and for the Chapter. They will work with the board to post any communications regarding events, lectures, updates, and more in a timely manner. They will also be responsible, along with the Communications Director and Executive Board, to respond to any feedback received on these channels.

**Comment by aigapresident** [comment]
Here's the Development Director Descriptor

The Development Director fosters a relationship of mutual benefit between between AIGA Austin and representatives from allied fields who service the design community. This usually occurs in the form of cash or in-kind sponsorship for Chapter events. He/she will work closely with the Programming Director in establishing a calendar and identifying potential sponsors for Chapter events and activities. The Development Director works closely with a development committee to accomplish development goals.

**Comment by poofichu** [comment]
Added!
