### ISSUE TITLE
Afterhours Submission Information

### ISSUE THREAD

**Issue by cameronsandage** [AIGA-Austin/website#56]
Have y'all thought about creating a "submission template" for github that will be created for each issue? Random thoughts, don't kill me...

Also I probably made this more complicated then it needs to be. 

___________

**Title**  _-- (For Gitlab Formatting Only) --_

Call for Submissions | Afterhours 2018

**Hero Image**  _-- (For Gitlab Formatting Only) --_

![afterhoursaiga_image](https://user-images.githubusercontent.com/10966222/43497950-525aa61e-950a-11e8-824f-ed75c7a3f5cd.jpg)

**Copy** _-- (For Gitlab Formatting Only) --_

## **Be An Artist for Afterhours 2018**
Applying to Afterhours is super easy, and should take less than 10 minutes. The only requirement is you must reside in Central Texas.

Once the call for submissions closes, our awesome panel of judges (yet to be announced) will work on selecting the final 40 artist for the show. Your name will be removed from your submission and the judges won’t know whose work they’re viewing. Don’t worry about being “good enough.” Submit and see what happens, we’ve had a lot of first timers in the show!

### How to Apply:
Applying to Afterhours is done in three steps, you'll do this on the Typeform linked below:

#### Find three pieces of prior work that show off your skills and style.
You do not need to create any new work for this submission. 

#### Submit your three images as .jpg, .png or. tiff images and label them: LastName_(1-3).whatever.
Naming your files this way will help speed up the judging process.

#### Hit submit and your done!	

[**Submit Here** ](https://aigaaustin.typeform.com/to/YaIhyL)

_Submissions to close on August 29th, @ 11:59pm_
_________

## **What is Afterhours?**
_Afterhours is a poster party off the clock. It's part individual creative expression, part curated poster show, and part non-profit fundraiser._

The Afterhours poster show aims to bring together the central Texas community around a given local non-profit every year. The goal is to raise awareness for the non-profit and also provide some financial support through poster sales at the event each November.

Follow us on Social Media: 
@afterhoursatx ([twitter](https://twitter.com/AfterhoursATX) | [instragram](https://www.instagram.com/afterhoursatx/))
[facebook.com/afterhoursatx](https://www.facebook.com/afterhoursatx)

## **When's the Event?**
**Event Details:** 
Wright Bro. Brew & Brew
500 San Marcos St #105, Austin, TX 78702
![brewbrew-logo_afterhours2](https://user-images.githubusercontent.com/10966222/43498048-b9b905bc-950a-11e8-9f9e-6f3137c86036.jpg)

**Opening Night:**
November, 9th - Time TBD

**EAST Weekends:**
November, 10-11th - 11am - 6pm
November, 17-18th - 11am-6pm

**Comment by cameronsandage** [comment]
@poofichu Alisha Moore had an edit, I made the edit to the above. Thank you.

**Comment by poofichu** [comment]
Published! https://austin.aiga.org/event-internal/be-an-artist-for-afterhours-2018/
