### ISSUE TITLE
Fellow Event Page: Update

### ISSUE THREAD

**Issue by aigapresident** [AIGA-Austin/website#59]
Change first paragraph on website to read:

The AIGA Austin chapter welcomes you to an evening of celebration as we induct our two new AIGA Fellow honorees, **Herman Dyal** of Page/Dyal and **David Kampa** of McGarrah Jessee.

https://austin.aiga.org/event/2018-aiga-fellows-awards-gala/

**Comment by poofichu** [comment]
Updated!
