### ISSUE TITLE
Open Board Positions

### ISSUE THREAD

**Issue by aigapresident** [AIGA-Austin/website#60]
Please update https://austin.aiga.org/board-nominations-now-open/ with new open positions and description below. Typeform link here>> https://aigaaustin.typeform.com/to/GseuoA

**Membership Director**
The Membership Director aims to maintain and grow the local membership. In essence, this is the indirect responsibility of every Board member, but the Membership Director leads any recruiting/membership drive initiatives. The Director does this primarily by maintaining tools and reports that assist with communicating to lapsing members and by creating and using tools that demonstrate the value of membership.

**Development Director**
The Development Director fosters a relationship of mutual benefit between between AIGA Austin and
representatives from allied fields who service the design community. This usually occurs in the form of cash or in-kind sponsorship for Chapter events. He/she will work closely with the Programming Director in establishing a calendar and identifying potential sponsors for Chapter events and activities.

**Comment by poofichu** [comment]
Updated! https://austin.aiga.org/board-nominations-now-open/
