### ISSUE TITLE
MRK Webpage Updates 

### ISSUE THREAD

**Issue by crystalglover** [AIGA-Austin/website#71]
I updated the MRK page copy: https://docs.google.com/document/d/11cK2U7YkACClR7Jh6dPFUs_dNP6ApjV9-4NPD885Hbw

- Changed the first line about applications 
- Under About, changed the last word to “communities.”
- Rewrote the Awards section
- Updated Application section

Can we update? Thank you!

**Comment by poofichu** [comment]
@crystalglover can you give me permission to view the doc?

**Comment by poofichu** [comment]
Updated! https://austin.aiga.org/scholarships/aiga-maura-rose-kampa-scholarship/
