### ISSUE TITLE
Updates to Changemaker Series sidebar

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#74]
**Applications**
Applications for the 2019 Changemaker Series are now open! 
[Application for Creative Team Participants](https://aigaaustin.typeform.com/to/qVolxn)
[Application for Nonprofit and Change Organization Partners](https://aigaaustin.typeform.com/to/lDK5LW)

[Sign-up for our email list](http://eepurl.com/dm5Cg1) to stay up-to-date on AIGA Austin’s Changemaker Series!

**Comment by poofichu** [comment]
@Zac-Heckmann I'm going to assign these to you!
