### ISSUE TITLE
Remove application link for change organizations from Changemaker sidebar

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/website#75]
Please replace the copy/link under "Applications" in the Changemaker sidebar to the below:

[Applications for the 2019 Changemaker Series Creative Team Participation close on April 22nd.](https://aigaaustin.typeform.com/to/qVolxn)

Application for Nonprofit and Change Organization Partners are closed.

**Comment by poofichu** [comment]
Updated!
