### ISSUE TITLE
Afterhours Domain Transfer

### ISSUE THREAD

**Issue by alishalm** [AIGA-Austin/website#83]
Received this email in regards to the Afterhours domain transfer. Unfortunately, I don't have much background on this issue

--------------------------

A domain you’ve registered with Media Temple is due for renewal in 90 days. We want to make sure you have a chance to review your domain’s pricing before your renewal date, as it may have changed since your last renewal.

AFFECTED SERVICE
Domain: afterhoursatx.com
Renews on: 2019-08-12
Rate: $18.00/year

**WHAT YOU SHOULD DO**
If you want to keep this domain, you don’t need to do anything. The new renewal rate will be applied automatically. You can learn more in this Knowledge Base article:
https://mediatemple.net/community/products/all/204405714

If you don’t want to renew this domain, you’ll need to log in and request to close it in your Account Center:
https://ac.mediatemple.net/request_to_close/list.mt

Please rest assured that we’ve kept all domain price changes as low as possible. Thank you for your understanding, and thanks again for choosing Media Temple. Please feel free to contact us if you have any questions or need help.
http://mediatemple.net/help

**Comment by poofichu** [comment]
Supposedly tech support took care of this and completed the transfer to GoDaddy - If there are any other emails, contact them and make sure that Media Temple isn't handling this domain anymore.
