### ISSUE TITLE
Add Design Ranch Registration to Homepage Banner

### ISSUE THREAD

**Issue by poofichu** [AIGA-Austin/website#90]
We need to promote registration of Design Ranch - can we add it to either the homepage banner or as an event? However you feel is best, Zac.

## Copy:
Registration for Design Ranch 2020 is right around the corner! Mark those calendars for November 1st at 12pm central and make sure your AIGA membership login credentials are at your fingertips. You don’t have to be an AIGA member to attend Design Ranch, but it saves you $50 at registration. So why not? Become a member, sign up, and save a few bucks. Registration fees and other details can be found at designranch.org. Looking forward to seeing y’all at the ranch!

## Image:
![DR2020_RegistrationFacebookCover](https://user-images.githubusercontent.com/6757613/66161599-4b51a900-e5f2-11e9-8197-dc6ff4bd90f6.jpg)

## Links to:
http://www.designranch.org

**Comment by Zac-Heckmann** [comment]
complete
