### ISSUE TITLE
Add Code of Conduct and reporting to site

### ISSUE THREAD

**Issue by bripenney** [AIGA-Austin/website#95]
We need to add the code of conduct directly into our site linked in the footer and under About. In addition, we need to add the reporting form link to the site on the same page. https://aigaaustin.typeform.com/to/a1gzEx
https://docs.google.com/document/d/1uxecdIn0vLSfMZ8SP_-32TVDhtPZTeTIaOCtU8etHSs/edit?usp=sharing

**Comment by bripenney** [comment]
@poofichu can we also make sure Design Ranch is updated with this content?

**Comment by poofichu** [comment]
Done! https://designranch.org/code-of-conduct/
